version: '2'
services:
  genconfig:
    image: kylemanna/openvpn
    volumes:
      - data:/etc/openvpn
    command: ovpn_genconfig -u udp://vpn.cgcgbcbc.com
  init:
    image: kylemanna/openvpn
    volumes:
      - data:/etc/openvpn
    command: ovpn_initpki
  server:
    image: kylemanna/openvpn
    volumes:
      - data:/etc/openvpn
    cap_add:
      - NET_ADMIN
    restart: always
    ports:
      - "1194:1194/udp"
  gen:
    image: kylemanna/openvpn
    volumes:
      - data:/etc/openvpn
  modify:
    image: ubuntu
    volumes:
      - data:/etc/openvpn
    command: bash
    working_dir: /etc/openvpn
volumes:
  data:
    driver: local
